[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "storage-client"
version = "0.1.0"
description = "S3 and R2 storage client"
requires-python = ">=3.7"
dependencies = [
    "boto3>=1.26.0"
]